services:
  - type: web
    name: node-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_FROM
        value: info@yourdomain.com